name: workqueue
on: push
jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: npm install for workqueue
        run: npm install
      - name: build
        run: npm run build 
      - name: test
        run: npm run test
